parameters:
#    the_fireflies_user.example.class: TheFireflies\UserBundle\Example

services:
#    the_fireflies_user.example:
#        class: %the_fireflies_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
