<?php

namespace TheFireflies\SportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SportMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportMatchRepository extends EntityRepository
{
}
