friendlymatch:
    pattern:  /
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyMatch:index" }

friendlymatch_show:
    pattern:  /{id}/show
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyMatch:show" }

friendlymatch_new:
    pattern:  /new
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyMatch:new" }

friendlymatch_create:
    pattern:  /create
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyMatch:create" }
    requirements: { _method: post }

friendlymatch_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyMatch:edit" }

friendlymatch_update:
    pattern:  /{id}/update
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyMatch:update" }
    requirements: { _method: post|put }

friendlymatch_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyMatch:delete" }
    requirements: { _method: post|delete }
