friendlyevent:
    pattern:  /
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyEvent:index" }

friendlyevent_show:
    pattern:  /{id}/show
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyEvent:show" }

friendlyevent_new:
    pattern:  /new
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyEvent:new" }

friendlyevent_create:
    pattern:  /create
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyEvent:create" }
    requirements: { _method: post }

friendlyevent_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyEvent:edit" }

friendlyevent_update:
    pattern:  /{id}/update
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyEvent:update" }
    requirements: { _method: post|put }

friendlyevent_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TheFirefliesSportBundle:FriendlyEvent:delete" }
    requirements: { _method: post|delete }
