instanceteam:
    pattern:  /
    defaults: { _controller: "TheFirefliesSportBundle:InstanceTeam:index" }

instanceteam_show:
    pattern:  /{id}/show
    defaults: { _controller: "TheFirefliesSportBundle:InstanceTeam:show" }

instanceteam_create:
    pattern:  /create/{teamId}/new-instance-team
    defaults: { _controller: "TheFirefliesSportBundle:InstanceTeam:create" }
    requirements: { _method: post }

instanceteam_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TheFirefliesSportBundle:InstanceTeam:edit" }

instanceteam_update:
    pattern:  /{id}/update
    defaults: { _controller: "TheFirefliesSportBundle:InstanceTeam:update" }
    requirements: { _method: post|put }

instanceteam_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TheFirefliesSportBundle:InstanceTeam:delete" }
    requirements: { _method: post|delete }

playerdetail_new:
    pattern:  /{instanceTeamId}/new-player-detail
    defaults: { _controller: "TheFirefliesSportBundle:PlayerDetail:new" }