sport:
    pattern:  /
    defaults: { _controller: "TheFirefliesSportBundle:Sport:index" }

sport_show:
    pattern:  /{id}/show
    defaults: { _controller: "TheFirefliesSportBundle:Sport:show" }

sport_new:
    pattern:  /new
    defaults: { _controller: "TheFirefliesSportBundle:Sport:new" }

sport_create:
    pattern:  /create
    defaults: { _controller: "TheFirefliesSportBundle:Sport:create" }
    requirements: { _method: post }

sport_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TheFirefliesSportBundle:Sport:edit" }

sport_update:
    pattern:  /{id}/update
    defaults: { _controller: "TheFirefliesSportBundle:Sport:update" }
    requirements: { _method: post|put }

sport_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TheFirefliesSportBundle:Sport:delete" }
    requirements: { _method: post|delete }
