TheFirefliesSportBundle_sport:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/sport.yml"
    prefix:   /sport

home:
    pattern:  /
    defaults: { _controller: "TheFirefliesSportBundle:Home:index" }
