# Imports
TheFirefliesSportBundle_sport:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/sport.yml"
    prefix:   /sport

TheFirefliesSportBundle_club:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/club.yml"
    prefix:   /club

TheFirefliesSportBundle_team:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/team.yml"
    prefix:   /team

TheFirefliesSportBundle_event:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/event.yml"
    prefix:   /event

TheFirefliesSportBundle_friendlymatch:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/friendlymatch.yml"
    prefix:   /friendlymatch

TheFirefliesSportBundle_instanceteam:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/instanceteam.yml"
    prefix:   /instanceteam

TheFirefliesSportBundle_playerdetail:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/playerdetail.yml"
    prefix:   /playerdetail

# Home
home:
    pattern:  /
    defaults: { _controller: "TheFirefliesSportBundle:Home:index" }
