TheFirefliesSportBundle_sport:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/sport.yml"
    prefix:   /sport

TheFirefliesSportBundle_club:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/club.yml"
    prefix:   /club

TheFirefliesSportBundle_team:
    resource: "@TheFirefliesSportBundle/Resources/config/routing/team.yml"
    prefix:   /team

home:
    pattern:  /
    defaults: { _controller: "TheFirefliesSportBundle:Home:index" }
