TheFireflies\SportBundle\Entity\Sport:
    properties:
        name:
            - NotBlank: ~
        nbPlayersMin:
            - Range:
                min: 1
                max: 30
                minMessage: Un minimum de un joueur est requis.
                maxMessage: 30 joueurs maximum par équipe est autorisé.
        nbPlayersMax:
            - Range:
                min: 1
                max: 30
                minMessage: Un minimum de un joueur est requis.
                maxMessage: 30 joueurs maximum par équipe est autorisé.

TheFireflies\SportBundle\Entity\Club:
    properties:
        name:
            - NotBlank: ~
        website:
            - Url:
