TheFireflies\SportBundle\Entity\Club:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        teams:
            targetEntity: Team
            mappedBy: club
    fields:
        name:
            type: string
            length: 255
        website:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
