TheFireflies\SportBundle\Entity\Sport:
    type: entity
    table: sport
    repositoryClass: TheFireflies\SportBundle\Entity\SportRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
            nullable: false
        nbPlayersMin:
            type: smallint
        nbPlayersMax:
            type: smallint
    lifecycleCallbacks: {  }
