TheFireflies\SportBundle\Entity\Team:
    type: entity
    table: null
    repositoryClass: TheFireflies\SportBundle\Entity\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        club:
            targetEntity: Club
            inversedBy: teams
    fields:
        name:
            type: string
            length: 255
        division:
            type: string
            length: 255
            nullable: true
        website:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
